# Playground for Data Leakage

- Stephen W. Thomas
- Used for MMA 869, MMAI 869, and GMMA 869

In [1]:
import datetime
print(datetime.datetime.now())

2021-11-11 15:09:39.663158

In [5]:
import sklearn
sklearn.__version__

'0.22.2.post1'

In [6]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# disable chained assignments
pd.options.mode.chained_assignment = None

# Load Data

In [7]:
df = pd.read_csv('https://raw.githubusercontent.com/stepthom/869_course/main/data/GermanCredit.csv')
df['Class'] = df['Class'].map({'Good': 1, 'Bad': 0})
df['Salary'] = df['Amount']
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 63 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Duration                                1000 non-null   int64
 1   Amount                                  1000 non-null   int64
 2   InstallmentRatePercentage               1000 non-null   int64
 3   ResidenceDuration                       1000 non-null   int64
 4   Age                                     1000 non-null   int64
 5   NumberExistingCredits                   1000 non-null   int64
 6   NumberPeopleMaintenance                 1000 non-null   int64
 7   Telephone                               1000 non-null   int64
 8   ForeignWorker                           1000 non-null   int64
 9   Class                                   1000 non-null   int64
 10  CheckingAccountStatus.lt.0              1000 non-null   int64
 11  CheckingAccountStatus.0.to.200          1000 non-null   int64
 12  CheckingAccountStatus.gt.200            1000 non-null   int64
 13  CheckingAccountStatus.none              1000 non-null   int64
 14  CreditHistory.NoCredit.AllPaid          1000 non-null   int64
 15  CreditHistory.ThisBank.AllPaid          1000 non-null   int64
 16  CreditHistory.PaidDuly                  1000 non-null   int64
 17  CreditHistory.Delay                     1000 non-null   int64
 18  CreditHistory.Critical                  1000 non-null   int64
 19  Purpose.NewCar                          1000 non-null   int64
 20  Purpose.UsedCar                         1000 non-null   int64
 21  Purpose.Furniture.Equipment             1000 non-null   int64
 22  Purpose.Radio.Television                1000 non-null   int64
 23  Purpose.DomesticAppliance               1000 non-null   int64
 24  Purpose.Repairs                         1000 non-null   int64
 25  Purpose.Education                       1000 non-null   int64
 26  Purpose.Vacation                        1000 non-null   int64
 27  Purpose.Retraining                      1000 non-null   int64
 28  Purpose.Business                        1000 non-null   int64
 29  Purpose.Other                           1000 non-null   int64
 30  SavingsAccountBonds.lt.100              1000 non-null   int64
 31  SavingsAccountBonds.100.to.500          1000 non-null   int64
 32  SavingsAccountBonds.500.to.1000         1000 non-null   int64
 33  SavingsAccountBonds.gt.1000             1000 non-null   int64
 34  SavingsAccountBonds.Unknown             1000 non-null   int64
 35  EmploymentDuration.lt.1                 1000 non-null   int64
 36  EmploymentDuration.1.to.4               1000 non-null   int64
 37  EmploymentDuration.4.to.7               1000 non-null   int64
 38  EmploymentDuration.gt.7                 1000 non-null   int64
 39  EmploymentDuration.Unemployed           1000 non-null   int64
 40  Personal.Male.Divorced.Seperated        1000 non-null   int64
 41  Personal.Female.NotSingle               1000 non-null   int64
 42  Personal.Male.Single                    1000 non-null   int64
 43  Personal.Male.Married.Widowed           1000 non-null   int64
 44  Personal.Female.Single                  1000 non-null   int64
 45  OtherDebtorsGuarantors.None             1000 non-null   int64
 46  OtherDebtorsGuarantors.CoApplicant      1000 non-null   int64
 47  OtherDebtorsGuarantors.Guarantor        1000 non-null   int64
 48  Property.RealEstate                     1000 non-null   int64
 49  Property.Insurance                      1000 non-null   int64
 50  Property.CarOther                       1000 non-null   int64
 51  Property.Unknown                        1000 non-null   int64
 52  OtherInstallmentPlans.Bank              1000 non-null   int64
 53  OtherInstallmentPlans.Stores            1000 non-null   int64
 54  OtherInstallmentPlans.None              1000 non-null   int64
 55  Housing.Rent                            1000 non-null   int64
 56  Housing.Own                             1000 non-null   int64
 57  Housing.ForFree                         1000 non-null   int64
 58  Job.UnemployedUnskilled                 1000 non-null   int64
 59  Job.UnskilledResident                   1000 non-null   int64
 60  Job.SkilledEmployee                     1000 non-null   int64
 61  Job.Management.SelfEmp.HighlyQualified  1000 non-null   int64
 62  Salary                                  1000 non-null   int64
dtypes: int64(63)
memory usage: 492.3 KB

   Duration  Amount  ...  Job.Management.SelfEmp.HighlyQualified  Salary
0         6    1169  ...                                       0    1169
1        48    5951  ...                                       0    5951
2        12    2096  ...                                       0    2096
3        42    7882  ...                                       0    7882
4        24    4870  ...                                       0    4870

[5 rows x 63 columns]

In [8]:
from sklearn.model_selection import train_test_split

X = df.drop(['Class'], axis=1)
y = df[['Class']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)